// <auto-generated />
using System;
using System.Collections.Generic;
using DikuWeb.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DikuWeb.Persistence.Migrations
{
    [DbContext(typeof(DikuWebDbContext))]
    [Migration("20260805151713_AddBuilderSupport")]
    partial class AddBuilderSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DikuWeb.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("BanReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ban_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_username");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Building.ContentAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("action");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("entity_key");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("entity_kind");

                    b.HasKey("Id");

                    b.HasIndex("EntityKind", "EntityKey", "At")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_content_audit_entity");

                    b.ToTable("content_audit", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("path");

                    b.Property<long>("PlaytimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("playtime_seconds");

                    b.Property<string>("RoomKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("room_key");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_characters_account_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_name");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.Room", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("EditorX")
                        .HasColumnType("integer")
                        .HasColumnName("editor_x");

                    b.Property<int?>("EditorY")
                        .HasColumnType("integer")
                        .HasColumnName("editor_y");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.PrimitiveCollection<List<string>>("Grid")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("grid");

                    b.Property<string>("Legend")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("legend");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.Property<string>("ZoneKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("zone_key");

                    b.HasKey("Key");

                    b.HasIndex("ZoneKey")
                        .HasDatabaseName("ix_rooms_zone_key");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.RoomExit", b =>
                {
                    b.Property<string>("FromRoomKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("from_room_key");

                    b.Property<string>("Direction")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("direction");

                    b.Property<string>("ToRoomKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("to_room_key");

                    b.HasKey("FromRoomKey", "Direction");

                    b.HasIndex("ToRoomKey")
                        .HasDatabaseName("ix_room_exits_to_room_key");

                    b.ToTable("room_exits", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.World", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Key");

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.Zone", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer")
                        .HasColumnName("max_level");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer")
                        .HasColumnName("min_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("WorldKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("world_key");

                    b.HasKey("Key");

                    b.HasIndex("WorldKey")
                        .HasDatabaseName("ix_zones_world_key");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Characters.Character", b =>
                {
                    b.HasOne("DikuWeb.Domain.Accounts.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DikuWeb.Domain.Characters.AttributeSet", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Agility");

                            b1.Property<int>("Insight");

                            b1.Property<int>("Might");

                            b1.Property<int>("Resolve");

                            b1.Property<int>("Vitality");

                            b1.HasKey("CharacterId");

                            b1.ToTable("characters");

                            b1
                                .ToJson("attributes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("DikuWeb.Domain.Characters.Vitals", "Vitals", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Focus");

                            b1.Property<int>("FocusMax");

                            b1.Property<int>("Health");

                            b1.Property<int>("HealthMax");

                            b1.Property<int>("Stamina");

                            b1.Property<int>("StaminaMax");

                            b1.HasKey("CharacterId");

                            b1.ToTable("characters");

                            b1
                                .ToJson("vitals")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Vitals")
                        .IsRequired();
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.Room", b =>
                {
                    b.HasOne("DikuWeb.Domain.Worlds.Zone", "Zone")
                        .WithMany("Rooms")
                        .HasForeignKey("ZoneKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.RoomExit", b =>
                {
                    b.HasOne("DikuWeb.Domain.Worlds.Room", "FromRoom")
                        .WithMany("Exits")
                        .HasForeignKey("FromRoomKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromRoom");
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.Zone", b =>
                {
                    b.HasOne("DikuWeb.Domain.Worlds.World", "World")
                        .WithMany("Zones")
                        .HasForeignKey("WorldKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("DikuWeb.Domain.Accounts.Account", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.Room", b =>
                {
                    b.Navigation("Exits");
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.World", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.Zone", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
