// <auto-generated />
using System;
using System.Collections.Generic;
using DikuWeb.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DikuWeb.Persistence.Migrations
{
    [DbContext(typeof(DikuWebDbContext))]
    partial class DikuWebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DikuWeb.Domain.Abilities.Ability", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<long?>("CastTimePulses")
                        .HasColumnType("bigint")
                        .HasColumnName("cast_time_pulses");

                    b.Property<long>("CooldownPulses")
                        .HasColumnType("bigint")
                        .HasColumnName("cooldown_pulses");

                    b.Property<int>("CostType")
                        .HasColumnType("integer")
                        .HasColumnName("cost_type");

                    b.Property<int>("CostValue")
                        .HasColumnType("integer")
                        .HasColumnName("cost_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EffectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effect_key");

                    b.Property<Dictionary<string, string>>("EffectParams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("effect_params");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TargetingType")
                        .HasColumnType("integer")
                        .HasColumnName("targeting_type");

                    b.HasKey("Key")
                        .HasName("pk_abilities");

                    b.HasIndex("TargetingType")
                        .HasDatabaseName("ix_abilities_targeting_type");

                    b.ToTable("abilities", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("BanReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ban_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_username");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Accounts.AdminAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_account_id");

                    b.Property<string>("After")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("after");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Before")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("before");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TargetAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_account_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_audit");

                    b.HasIndex("TargetAccountId", "At")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_admin_audit_target");

                    b.ToTable("admin_audit", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Building.ContentAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("action");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("entity_key");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("entity_kind");

                    b.HasKey("Id")
                        .HasName("pk_content_audit");

                    b.HasIndex("EntityKind", "EntityKey", "At")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_content_audit_entity");

                    b.ToTable("content_audit", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("CombatState")
                        .HasColumnType("integer")
                        .HasColumnName("combat_state");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentTarget")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_target");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint")
                        .HasColumnName("gold");

                    b.Property<DateTimeOffset?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("path");

                    b.Property<long>("PlaytimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("playtime_seconds");

                    b.Property<string>("RespawnRoomKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("respawn_room_key");

                    b.Property<int>("RestState")
                        .HasColumnType("integer")
                        .HasColumnName("rest_state");

                    b.Property<string>("RoomKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("room_key");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint")
                        .HasColumnName("xp");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_characters_account_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_name");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Inhabitants.Mob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CombatState")
                        .HasColumnType("integer")
                        .HasColumnName("combat_state");

                    b.Property<string>("CurrentTarget")
                        .HasColumnType("text")
                        .HasColumnName("current_target");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("ResolvedGold")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_gold");

                    b.Property<Dictionary<string, object>>("ResolvedStats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resolved_stats");

                    b.Property<int>("ResolvedXp")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_xp");

                    b.Property<string>("RoomKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_key");

                    b.Property<Dictionary<string, decimal>>("SpawnMultipliers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("spawn_multipliers");

                    b.Property<Guid?>("SpawnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("spawner_id");

                    b.Property<Dictionary<string, object>>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_key");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_name");

                    b.HasKey("Id")
                        .HasName("pk_mobs");

                    b.HasIndex("RoomKey")
                        .HasDatabaseName("ix_mobs_room_key");

                    b.ToTable("mobs", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Inhabitants.MobTemplate", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("BaseGold")
                        .HasColumnType("integer")
                        .HasColumnName("base_gold");

                    b.Property<Dictionary<string, object>>("BaseStats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("base_stats");

                    b.Property<int>("BaseXp")
                        .HasColumnType("integer")
                        .HasColumnName("base_xp");

                    b.Property<Dictionary<string, object>>("Behavior")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("behavior");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<List<Dictionary<string, object>>>("Loot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("loot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("WanderIntervalPulses")
                        .HasColumnType("integer")
                        .HasColumnName("wander_interval_pulses");

                    b.HasKey("Key")
                        .HasName("pk_mob_templates");

                    b.ToTable("mob_templates", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Items.ItemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContainerItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_item_id");

                    b.Property<int?>("EquippedSlot")
                        .HasColumnType("integer")
                        .HasColumnName("equipped_slot");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<Guid?>("OwnerCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_character_id");

                    b.Property<Dictionary<string, object>>("ResolvedStats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resolved_stats");

                    b.Property<string>("RoomKey")
                        .HasColumnType("text")
                        .HasColumnName("room_key");

                    b.Property<Dictionary<string, decimal>>("SpawnMultipliers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("spawn_multipliers");

                    b.Property<Guid?>("SpawnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("spawner_id");

                    b.Property<Dictionary<string, object>>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_key");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_name");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_item_instances");

                    b.HasIndex("OwnerCharacterId")
                        .HasDatabaseName("ix_item_instances_owner_character_id");

                    b.HasIndex("RoomKey")
                        .HasDatabaseName("ix_item_instances_room_key");

                    b.ToTable("item_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_instance_location", "(num_nonnulls(owner_character_id, container_item_id, room_key) = 1)");
                        });
                });

            modelBuilder.Entity("DikuWeb.Domain.Items.ItemTemplate", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<Dictionary<string, object>>("BaseStats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("base_stats");

                    b.Property<int>("BaseValue")
                        .HasColumnType("integer")
                        .HasColumnName("base_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Key")
                        .HasName("pk_item_templates");

                    b.ToTable("item_templates", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Quests.CharacterQuest", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("QuestKey")
                        .HasColumnType("text")
                        .HasColumnName("quest_key");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TimesCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("times_completed");

                    b.HasKey("CharacterId", "QuestKey")
                        .HasName("pk_character_quests");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_character_quests_character_id");

                    b.HasIndex("CharacterId", "Status")
                        .HasDatabaseName("ix_character_quests_character_id_status")
                        .HasFilter("status = 'Active'");

                    b.ToTable("character_quests", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Quests.Quest", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Dictionary<string, string>>("Dialogue")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dialogue");

                    b.Property<string>("GiverMobKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("giver_mob_key");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_repeatable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("PrerequisiteQuestKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("prerequisite_quest_keys");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("integer")
                        .HasColumnName("required_count");

                    b.Property<string>("RequiredItemKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_item_key");

                    b.Property<int>("RewardGold")
                        .HasColumnType("integer")
                        .HasColumnName("reward_gold");

                    b.Property<int>("RewardItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("reward_item_count");

                    b.Property<string>("RewardItemKey")
                        .HasColumnType("text")
                        .HasColumnName("reward_item_key");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer")
                        .HasColumnName("reward_xp");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("TurninMobKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turnin_mob_key");

                    b.Property<string>("ZoneKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_key");

                    b.HasKey("Key")
                        .HasName("pk_quests");

                    b.HasIndex("GiverMobKey")
                        .HasDatabaseName("ix_quests_giver_mob_key");

                    b.HasIndex("TurninMobKey")
                        .HasDatabaseName("ix_quests_turnin_mob_key");

                    b.ToTable("quests", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Spawning.Spawner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("RespawnSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("respawn_seconds");

                    b.PrimitiveCollection<List<string>>("RoomKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("room_keys");

                    b.Property<bool>("Sentinel")
                        .HasColumnType("boolean")
                        .HasColumnName("sentinel");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer")
                        .HasColumnName("target_count");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_key");

                    b.Property<int>("TemplateKind")
                        .HasColumnType("integer")
                        .HasColumnName("template_kind");

                    b.Property<string>("ZoneKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_key");

                    b.HasKey("Id")
                        .HasName("pk_spawners");

                    b.HasIndex("ZoneKey")
                        .HasDatabaseName("ix_spawners_zone_key");

                    b.ToTable("spawners", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.Room", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("EditorX")
                        .HasColumnType("integer")
                        .HasColumnName("editor_x");

                    b.Property<int?>("EditorY")
                        .HasColumnType("integer")
                        .HasColumnName("editor_y");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.PrimitiveCollection<List<string>>("Grid")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("grid");

                    b.Property<string>("Legend")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("legend");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.Property<string>("ZoneKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("zone_key");

                    b.HasKey("Key")
                        .HasName("pk_rooms");

                    b.HasIndex("ZoneKey")
                        .HasDatabaseName("ix_rooms_zone_key");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.RoomExit", b =>
                {
                    b.Property<string>("FromRoomKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("from_room_key");

                    b.Property<string>("Direction")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("direction");

                    b.Property<string>("ToRoomKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("to_room_key");

                    b.HasKey("FromRoomKey", "Direction")
                        .HasName("pk_room_exits");

                    b.HasIndex("ToRoomKey")
                        .HasDatabaseName("ix_room_exits_to_room_key");

                    b.ToTable("room_exits", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.World", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.Property<string>("Multipliers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("multipliers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Key")
                        .HasName("pk_worlds");

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.Zone", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer")
                        .HasColumnName("max_level");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer")
                        .HasColumnName("min_level");

                    b.Property<string>("Multipliers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("multipliers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("WorldKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("world_key");

                    b.HasKey("Key")
                        .HasName("pk_zones");

                    b.HasIndex("WorldKey")
                        .HasDatabaseName("ix_zones_world_key");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("DikuWeb.Domain.Characters.Character", b =>
                {
                    b.HasOne("DikuWeb.Domain.Accounts.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_accounts_account_id");

                    b.OwnsOne("DikuWeb.Domain.Characters.AttributeSet", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Agility");

                            b1.Property<int>("Insight");

                            b1.Property<int>("Might");

                            b1.Property<int>("Resolve");

                            b1.Property<int>("Vitality");

                            b1.HasKey("CharacterId");

                            b1.ToTable("characters");

                            b1
                                .ToJson("attributes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId")
                                .HasConstraintName("fk_characters_characters_character_id");
                        });

                    b.OwnsOne("DikuWeb.Domain.Characters.Vitals", "Vitals", b1 =>
                        {
                            b1.Property<Guid>("CharacterId");

                            b1.Property<int>("Focus");

                            b1.Property<int>("FocusMax");

                            b1.Property<int>("Health");

                            b1.Property<int>("HealthMax");

                            b1.Property<int>("Stamina");

                            b1.Property<int>("StaminaMax");

                            b1.HasKey("CharacterId");

                            b1.ToTable("characters");

                            b1
                                .ToJson("vitals")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId")
                                .HasConstraintName("fk_characters_characters_character_id");
                        });

                    b.Navigation("Account");

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Vitals")
                        .IsRequired();
                });

            modelBuilder.Entity("DikuWeb.Domain.Inhabitants.Mob", b =>
                {
                    b.OwnsOne("DikuWeb.Domain.Characters.Vitals", "Vitals", b1 =>
                        {
                            b1.Property<Guid>("MobId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Focus")
                                .HasColumnType("integer")
                                .HasColumnName("vitals_focus");

                            b1.Property<int>("FocusMax")
                                .HasColumnType("integer")
                                .HasColumnName("vitals_focus_max");

                            b1.Property<int>("Health")
                                .HasColumnType("integer")
                                .HasColumnName("vitals_health");

                            b1.Property<int>("HealthMax")
                                .HasColumnType("integer")
                                .HasColumnName("vitals_health_max");

                            b1.Property<int>("Stamina")
                                .HasColumnType("integer")
                                .HasColumnName("vitals_stamina");

                            b1.Property<int>("StaminaMax")
                                .HasColumnType("integer")
                                .HasColumnName("vitals_stamina_max");

                            b1.HasKey("MobId")
                                .HasName("pk_mobs");

                            b1.ToTable("mobs");

                            b1.WithOwner()
                                .HasForeignKey("MobId")
                                .HasConstraintName("fk_mobs_mobs_id");
                        });

                    b.Navigation("Vitals")
                        .IsRequired();
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.Room", b =>
                {
                    b.HasOne("DikuWeb.Domain.Worlds.Zone", "Zone")
                        .WithMany("Rooms")
                        .HasForeignKey("ZoneKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_zones_zone_key");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.RoomExit", b =>
                {
                    b.HasOne("DikuWeb.Domain.Worlds.Room", "FromRoom")
                        .WithMany("Exits")
                        .HasForeignKey("FromRoomKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_exits_rooms_from_room_key");

                    b.Navigation("FromRoom");
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.Zone", b =>
                {
                    b.HasOne("DikuWeb.Domain.Worlds.World", "World")
                        .WithMany("Zones")
                        .HasForeignKey("WorldKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zones_worlds_world_key");

                    b.Navigation("World");
                });

            modelBuilder.Entity("DikuWeb.Domain.Accounts.Account", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.Room", b =>
                {
                    b.Navigation("Exits");
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.World", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("DikuWeb.Domain.Worlds.Zone", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
