<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Muwbta.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\RepoPath.cs" Link="RepoPath.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Muwbta.Server\Muwbta.Server.csproj" />
    <ProjectReference Include="..\..\src\Muwbta.Persistence\Muwbta.Persistence.csproj" />
  </ItemGroup>

</Project>
